
language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 push될 때 수행할 지 지정
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 해당 디렉토리에 캐시하여
# 같은 의존성은 다음 배포때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 push되었을때 수행하는 명령어
# 프로젝트 내부의  gradlew 를 통해 clean&build를 수행함
script: "./gradlew clean build"

# permision denind 발생하여 추가
before_install:
  - chmod +x gradlew

# deploy 명령어 실행 전 수행
before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성, Travis CI는 특정파일만 업로드가 안되므로 디렉토리 항상 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cp before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/sbtest-springboot2-webservice.zip

# S3로 파일 업로드 또는 CodeDeploy로 배포 등 외부서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo setting 에 설정된 값
    bucket: sbtest-springboot2-build #s3 버킷
    region : ap-northeast-2
    skip_cleanup : true
    acl : private #zip 파일 접근을  private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 (해당위치의 파일들만 S3으로 전송)
    wait-until-deploy: true

# 빌드 성공 후 s3버킷에 zip 파일이 있는지 확인
# ==> Travis CI, S3 연동 완료

# EC2에 IAM역할 연결 후 재부팅
# EC2에 CodeDeploy 요청을 받을 수 있도록 에이전트 설치
# aws s3 cp s3://aws-codedeploy-ap-northeast-2/latest/install . --region ap-northeast-2
# chmod +x ./install
# sudo ./install auto
# sudo service codedeploy-agent status (agent 실행여부 확인)
# IAM 역할 생성 AWSCodeDeployRole
# AWS CodeDeploy 애플리케이션 생성

# .travis.yml : Travis CI 빌드 -> S3에 zip파일 전송
# appspec.yml : S3의 zip 파일을  EC2의 /home/ec2-user/app/step2/zip 경로로 복사하여 압축 푼다.

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: sbtest-springboot2-build # S3 버킷
    key: sbtest-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축확장자
    application: sbtest-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: sbtest-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# ==> Travis CI, S3, CodeDeploy 연동 완료
# ==> deploy.sh 작성 후 appspec.yml에 CodeDeploy 배포단계 실행스크립트 작성

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nikaido244@naver.com