
language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 push될 때 수행할 지 지정
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 해당 디렉토리에 캐시하여
# 같은 의존성은 다음 배포때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 push되었을때 수행하는 명령어
# 프로젝트 내부의  gradlew 를 통해 clean&build를 수행함
script: "./gradlew clean build"

# permision denind 발생하여 추가
before_install:
  - chmod +x gradlew

# deploy 명령어 실행 전 수행
before_deploy:
  - zip -r sbtest-springboot2-webservice * # CodeDeploy 는 Jar 파일을 인식하지 못하므로 zip으로 압축
  - mkdir -p deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mv sbtest-springboot2-webservice.zip deploy/sbtest-springboot2-webservice.zip

# S3로 파일 업로드 또는 CodeDeploy로 배포 등 외부서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo setting 에 설정된 값
    bucket: sbtest-springboot2-build #s3 버킷
    region : ap-northeast-2
    skip_cleanup : true
    acl : private #zip 파일 접근을  private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 (해당위치의 파일들만 S3으로 전송)
    wait-until-deploy: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nikaido244@naver.com